# .streamlit/secrets.toml

[snowflake]
user = "your usernmae"
password = "your password"
account = "your account"
warehouse = "your warehouse"
database = "SNOWFLAKE"
schema = "INFORMATION_SCHEMA"
role = 'ACCOUNTADMIN'